[package]
name = "kampfkarren/hoarcekat"
version = "1.3.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Janitor = "howmanysmall/janitor@1.15.7"
Promise = "evaera/promise@4.0.0-rc.2"
ReductionUtility = "howmanysmall/reduction-utility@1.0.0"
Roact = "roblox/roact@1.4.4"
RoactHooked = "howmanysmall/roact-hooked-luau@0.1.0"
RoactRodux = "roblox/roact-rodux@0.5.1"
Rodux = "roblox/rodux@4.0.0-rc.0"
