[package]
name = "kampfkarren/hoarcekat"
version = "1.2.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Roact = "roblox/roact@1.4.2"
RoactRodux = "roblox/roact-rodux@0.5.1"
Rodux = "roblox/rodux@4.0.0-rc.0"
RoactHooked = "howmanysmall/roact-hooked-luau@0.1.0"
Janitor = "howmanysmall/janitor@1.15.1"
